title: Photo Screensaver
description: A Chrome extension Screensaver with multiple photo sources, including your Google Photos.
theme: jekyll-theme-cayman
markdown: kramdown
repository: opus1269/photo-screen-saver
google_analytics: UA-61314754-5
